name: pomodoro2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management & Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Notifications
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1

  # Vibration
  vibration: ^3.1.4
  device_info_plus: ^12.2.0

  # Keep Screen On
  wakelock_plus: ^1.2.1

  cupertino_icons: ^1.0.8

  # Other UI packages
  audioplayers: ^5.2.1
  do_not_disturb: 1.0.3
  intl: ^0.19.0
  confetti: ^0.7.0
  reorderables: ^0.6.0
  liquid_progress_indicator_v2: ^0.5.0
  flutter_confetti: ^0.2.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive model generator (to'g'ri joy!)
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avater.png
    - assets/icon.png
    - assets/sounds/

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"
